In [17]:
import numpy as np

## numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

## 1. 연산함수
- add, substract, multiply, divide

In [31]:
import numpy as np

x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
z = np.arange(16).reshape(4, 4)

print(x)
print(y)
print(z)
print(x.shape, y.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.21027394 0.90798167 0.62244308 0.91003253 0.72500341]
 [0.67758915 0.47489529 0.83286494 0.80351639 0.21840662]
 [0.98530807 0.19956895 0.92952793 0.43970645 0.13768109]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(3, 5) (3, 5)


In [32]:
# 인덱스가 같은 원소끼리 더해짐. sahpe이 다른 경우는 error!
np.add(x, y)

array([[ 0.21027394,  1.90798167,  2.62244308,  3.91003253,  4.72500341],
       [ 5.67758915,  6.47489529,  7.83286494,  8.80351639,  9.21840662],
       [10.98530807, 11.19956895, 12.92952793, 13.43970645, 14.13768109]])

In [34]:
print(x)
print(z)
np.add(x, z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


ValueError: operands could not be broadcast together with shapes (3,5) (4,4) 

In [41]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)

print(x)
print(y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[4.76978470e-01 8.73471139e-01 6.17803004e-01 5.46342990e-01
  1.49310817e-02]
 [5.32305683e-01 3.56966930e-01 8.41167544e-01 4.60360494e-01
  2.72453670e-01]
 [2.56862554e-01 1.68326111e-05 5.40701150e-01 9.74520253e-01
  7.93580965e-01]]


array([[0.00000000e+00, 1.14485752e+00, 3.23727788e+00, 5.49105609e+00,
        2.67897536e+02],
       [9.39309905e+00, 1.68082797e+01, 8.32176663e+00, 1.73776857e+01,
        3.30331392e+01],
       [3.89313266e+01, 6.53493383e+05, 2.21934057e+01, 1.33398972e+01,
        1.76415522e+01]])

In [42]:
# 사칙연산은 함수보다는 바로 연산자를 이용한다.
# 기본적으로는 두 배열의 shaoe을 같아야 하는것만 주의(나중에 브로드 케스트 배운다,)
x+y

array([[ 0.47697847,  1.87347114,  2.617803  ,  3.54634299,  4.01493108],
       [ 5.53230568,  6.35696693,  7.84116754,  8.46036049,  9.27245367],
       [10.25686255, 11.00001683, 12.54070115, 13.97452025, 14.79358096]])

In [43]:
x-y

array([[-0.47697847,  0.12652886,  1.382197  ,  2.45365701,  3.98506892],
       [ 4.46769432,  5.64303307,  6.15883246,  7.53963951,  8.72754633],
       [ 9.74313745, 10.99998317, 11.45929885, 12.02547975, 13.20641904]])

In [44]:
x*y

array([[0.00000000e+00, 8.73471139e-01, 1.23560601e+00, 1.63902897e+00,
        5.97243269e-02],
       [2.66152841e+00, 2.14180158e+00, 5.88817281e+00, 3.68288396e+00,
        2.45208303e+00],
       [2.56862554e+00, 1.85158723e-04, 6.48841379e+00, 1.26687633e+01,
        1.11101335e+01]])

In [45]:
x/y

array([[0.00000000e+00, 1.14485752e+00, 3.23727788e+00, 5.49105609e+00,
        2.67897536e+02],
       [9.39309905e+00, 1.68082797e+01, 8.32176663e+00, 1.73776857e+01,
        3.30331392e+01],
       [3.89313266e+01, 6.53493383e+05, 2.21934057e+01, 1.33398972e+01,
        1.76415522e+01]])

**행렬(Matrix) 곱셈**
- **np.dot(array1, array2)** : 일반함수
- **array1.dot(array2)** : numpy.arrary type 멤버함수 
- **array1 @ array2**

In [24]:
np.dot(x,y)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [4]:
import numpy as np

x = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])
y = np.array([[1, 2],
              [3, 4],  
              [5, 6]])
x.shape, y.shape

((3, 3), (3, 2))

In [6]:
np.dot(x, y)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [7]:
x.dot(y)


array([[22, 28],
       [22, 28],
       [31, 40]])

In [10]:
y.dot(x) # 마주보는 행과 열이 같아야지만 실행된다.

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [9]:
x @ y

array([[22, 28],
       [22, 28],
       [31, 40]])

In [51]:
1*1 + 2*3 + 3*5

22

In [52]:
1*2 + 2*4 + 3*6

28

## 2. 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [11]:
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
#평균
# 멤버함수, 일반함수 둘다 가능. 모두 다되는건 아니다. 기본적인것은 있다.
# 왠만하면 np안에 있다. 멤버 함수로 없는 경우가 있다.
np.mean(y)

# mean = average

3.5

In [14]:
y.mean()

3.5

In [18]:
# 최대값
np.max(y)

6

In [21]:
# 가장 큰 값의 인덱스를 가져오고 싶을 때
# 다차원이지만 1차원으로 계산해서 인덱스를 가지고 온다.
np.argmax(y)


5

In [25]:
# 우리가 loop를 돌려서 구했던 것들 대부분 np 함수를 이용해서 구할 수 있다.
# 분산,    중앙값,       표준편차
np.var(y), np.median(y), np.std(y)

(2.9166666666666665, 3.5, 1.707825127659933)

## 3. 집계함수
 - 합계: sum()
 - 누적합계(Cumulative Sum): cumsum()

In [27]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.sum(y)

21

In [29]:
# 앞에 원소랑 자신의 합을 나타냄. 누적된 값을 그래프로 그릴때 유용
np.cumsum(y)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [31]:
# 각 행의 열끼리 더함. 파이썬 내장함수
sum(y)

[ 9 12]


array([4, 6])

In [37]:
# axis는 기본적으로 None -> 전체의 합을 구한다.
# axis가 0이면 행의 합을 구함 y(0,0)+y(1,0)+y(2,0),.....,y(0,4)+y(1,4)+y(2,4)
print(y)
np.sum(y, axis = 0)

[[1 2]
 [3 4]
 [5 6]]


array([ 9, 12])

In [40]:
# axis가 1이면 축의 합을 구함 y(0,0)+y(0,1)+y(0,2)+..+y(0,4), y(1,0)+...y(1,4), y(2,0)+..+y(2,4)
np.sum(y, axis = 1)

array([ 3,  7, 11])

## 4. any(), all()
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [47]:
z = np.random.randn(10) # 정규분포로 만들어줌.
print(z)

[ 1.56687846  0.46283012 -2.6870832  -0.38227659  1.18830064  0.66604726
  0.26414781 -0.15827277 -0.04851352 -0.75487587]


In [48]:
z > 0

array([ True,  True, False, False,  True,  True,  True, False, False,
       False])

In [49]:
# 조건이 하나라도 맞으면 참
np.any(z>0)

True

In [54]:
# 조건을 모두 만족해야 참
np.all(z>0)

False

In [55]:
np.all(z != 0)

True

## 5. where()
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우
 - numpy에서 많이 쓰이는 함수 중 하나

In [56]:
z = np.random.randn(10)
print(z)

[ 0.31276429  1.17001773 -1.20391028  0.77219005  0.76070795 -0.38068198
  1.25281069 -1.37407197  1.85708645 -1.49010559]


In [57]:
# 10개의 벡터에서 0보다 크면 그 값을 쓰고 아니면 0으로 바꾸고 싶어요.
np.where(z > 0, z, 0)


array([0.31276429, 1.17001773, 0.        , 0.77219005, 0.76070795,
       0.        , 1.25281069, 0.        , 1.85708645, 0.        ])

In [59]:
# 파이썬 이용하면 loop돌려서 비교하고 바꾸고..np 이용하면 쉽고 빠르게 사용가능!! 빠른성능, 적은 메모리
list_a = []

for i in z:
    if i > 0:
        list_a.append(i)
    else:
        list_a.append(0)
        

arr1 = np.array(list_a)
arr1

array([0.31276429, 1.17001773, 0.        , 0.77219005, 0.76070795,
       0.        , 1.25281069, 0.        , 1.85708645, 0.        ])

## 6. 정렬함수
### 6.1. 1차원 정렬

In [60]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 7, 9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

**np.sort(arr)**
- 기본적으로 오름차순 정렬
- 내림차순 : **np.sort(arr)[::-1]** 

In [61]:
np.sort(arr)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

하지만, 이 값들은 **유지가 되지 않습니다**!

In [65]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [70]:
arr2 = np.sort(arr)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
# sort 한 상태로 유지시키고 싶다면...
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 6.2. N차원 정렬

In [72]:
arr2d = np.array([[3, 8, 6, 5], 
                  [7, 4, 2, 1],
                  [10, 9, 12, 11]])
arr2d.shape

(3, 4)

#### 6.2.1. 열 정렬 (왼쪽에서 오른쪽으로)

In [73]:
np.sort(arr2d, axis=1)

array([[ 3,  5,  6,  8],
       [ 1,  2,  4,  7],
       [ 9, 10, 11, 12]])

In [78]:
np.sort(arr2d, axis=1)[::-1, :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  4,  7],
       [ 3,  5,  6,  8]])

In [79]:
np.sort(arr2d, axis=1)[:, ::-1]

array([[ 8,  6,  5,  3],
       [ 7,  4,  2,  1],
       [12, 11, 10,  9]])

In [80]:
np.sort(arr2d, axis=1)[::-1, ::-1]

array([[12, 11, 10,  9],
       [ 7,  4,  2,  1],
       [ 8,  6,  5,  3]])

#### 6.2.2. 행 정렬 (위에서 아래로)

In [82]:
print(arr2d)
np.sort(arr2d, axis=0)

[[ 3  8  6  5]
 [ 7  4  2  1]
 [10  9 12 11]]


array([[ 3,  4,  2,  1],
       [ 7,  8,  6,  5],
       [10,  9, 12, 11]])

### 6.3. index를 반환하는 argsort

- 정렬된 값을 반환하는 것이 아닌 index를 반환

In [100]:
arr2d = np.array([[3, 8, 6, 5], 
                  [7, 4, 2, 1],
                  [10, 9, 12, 11]])


#### 6.3.1. 열 정렬 (왼쪽에서 오른쪽으로)

In [101]:
print(np.sort(arr2d))
np.argsort(arr2d, axis = 1)

[[ 3  5  6  8]
 [ 1  2  4  7]
 [ 9 10 11 12]]


array([[0, 3, 2, 1],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

#### 6.3.2. 행 정렬

In [104]:
print(arr2d)
np.argsort(arr2d, axis = 0)

[[ 3  8  6  5]
 [ 7  4  2  1]
 [10  9 12 11]]


array([[0, 1, 1, 1],
       [1, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

# 7. 기타함수

In [106]:
z = np.random.randn(10)
print(z)

[-0.46617085 -0.97874383  0.3589386   0.26093385 -0.50792207  0.78698431
 -0.12489538 -0.00168621 -0.16440794 -1.27466367]


In [108]:
np.abs(z)

array([0.46617085, 0.97874383, 0.3589386 , 0.26093385, 0.50792207,
       0.78698431, 0.12489538, 0.00168621, 0.16440794, 1.27466367])

In [109]:
np.sign(z)

array([-1., -1.,  1.,  1., -1.,  1., -1., -1., -1., -1.])

In [110]:
np.sin(1), np.cos(1), np.tan(1)

(0.8414709848078965, 0.5403023058681398, 1.5574077246549023)